### ISSUE TITLE
Not networks enabled

### ISSUE THREAD

**Issue by JaviME7** [t3rn/executor-release#12]
Hi to all the community :)

I'm trying to run the latest version (0.29) with my wallet funded in all testnets, but the console is showing me the following error.

Anyone can help me?

Thanks in advanced and merry xmas :)

Best

---------

{"level":"info","time":1735159876739,"msg":"Enabled networks: arbitrum-sepolia, base-sepolia, optimism-sepolia, l1rn"}
{"level":"info","time":1735159876740,"networkId":"l1rn","msg":"✅ L3 network initialization"}
{"level":"info","time":1735159876740,"providersUrls":["https://brn.rpc.caldera.xyz/http"],"networkId":"l1rn","msg":"🔌 Initializing RPC provider"}
{"level":"info","time":1735159876754,"networkId":"l1rn","provider":"https://brn.rpc.caldera.xyz/http","msg":"🔌 Connected to RPC provider"}
{"level":"info","time":1735159877105,"networkId":"l1rn","singleAttestationBookContract":"0x450392B796A65FE542C0CDdBeb802f832e54Ac64","attestationBatchMakerContract":"0x9bf6931F78524c7c93Bcba6be4f99c4f5236Db81","msg":"🚧 Using V4 contracts for Attesting and Batching on L3"}
{"level":"debug","time":1735159877185,"msg":"Prometheus started on 9090"}
{"level":"debug","time":1735159878373,"insurance":"0","msg":"🏦 Current insurance on L3 network"}
{"level":"info","time":1735159878945,"supportRevertCommitments":false,"msg":"🏦 Support for revert commitments on L3 network"}
duplicate definition - Confirmation(bytes32,address,uint256,address,address)
{"level":"info","time":1735159878947,"providersUrls":["https://sepolia-rollup.arbitrum.io/rpc"],"networkId":"arbt","msg":"🔌 Initializing RPC provider"}
{"level":"info","time":1735159878948,"networkId":"arbt","provider":"https://sepolia-rollup.arbitrum.io/rpc","msg":"🔌 Connected to RPC provider"}
{"level":"info","time":1735159878969,"msg":"🔗 Connected to network arbt at {\"chainId\":6636130,\"name\":\"unknown\"}"}
{"level":"info","time":1735159878979,"attestationBatchMakerContract":"0x8723f8Bc333301dD1d36aF88a7651Bb9b2C62A66","msg":"🚧 Using V4 contracts for Attesting and Batching on Remote L3 network l0rn"}
{"level":"info","time":1735159879774,"address":"0xE77824881aC065C3C3a8779Ab82D599f147E5C40","sourceNetwork":"arbitrum-sepolia","balanceEth":"0.01","msg":"✅ Wallet loaded"}
duplicate definition - Confirmation(bytes32,address,uint256,address,address)
{"level":"error","time":1735159879787,"sourceNetwork":"arbt","balanceEth":"0.01","minBalanceThresholdEth":"0.1","msg":"🚨 Wallet balance is below the threshold. Disabling network."}
{"level":"info","time":1735159879787,"providersUrls":["https://base-sepolia.blockpi.network/v1/rpc/public"],"networkId":"bssp","msg":"🔌 Initializing RPC provider"}
{"level":"info","time":1735159879787,"networkId":"bssp","provider":"https://base-sepolia.blockpi.network/v1/rpc/public","msg":"🔌 Connected to RPC provider"}
{"level":"info","time":1735159879791,"msg":"🔗 Connected to network bssp at {\"chainId\":6636130,\"name\":\"unknown\"}"}
{"level":"info","time":1735159879801,"attestationBatchMakerContract":"0x8723f8Bc333301dD1d36aF88a7651Bb9b2C62A66","msg":"🚧 Using V4 contracts for Attesting and Batching on Remote L3 network l0rn"}
{"level":"info","time":1735159880636,"address":"0xE77824881aC065C3C3a8779Ab82D599f147E5C40","sourceNetwork":"base-sepolia","balanceEth":"0.01","msg":"✅ Wallet loaded"}
duplicate definition - Confirmation(bytes32,address,uint256,address,address)
{"level":"error","time":1735159880638,"sourceNetwork":"bssp","balanceEth":"0.01","minBalanceThresholdEth":"0.1","msg":"🚨 Wallet balance is below the threshold. Disabling network."}
{"level":"info","time":1735159880639,"providersUrls":["https://sepolia.optimism.io"],"networkId":"opsp","msg":"🔌 Initializing RPC provider"}
{"level":"info","time":1735159880639,"networkId":"opsp","provider":"https://sepolia.optimism.io","msg":"🔌 Connected to RPC provider"}
{"level":"info","time":1735159880641,"msg":"🔗 Connected to network opsp at {\"chainId\":6636130,\"name\":\"unknown\"}"}
{"level":"info","time":1735159880665,"attestationBatchMakerContract":"0x8723f8Bc333301dD1d36aF88a7651Bb9b2C62A66","msg":"🚧 Using V4 contracts for Attesting and Batching on Remote L3 network l0rn"}
{"level":"info","time":1735159881506,"address":"0xE77824881aC065C3C3a8779Ab82D599f147E5C40","sourceNetwork":"optimism-sepolia","balanceEth":"0.01","msg":"✅ Wallet loaded"}
{"level":"error","time":1735159881515,"sourceNetwork":"opsp","balanceEth":"0.01","minBalanceThresholdEth":"0.1","msg":"🚨 Wallet balance is below the threshold. Disabling network."}
{"level":"info","time":1735159881565,"attestationBatchMakerContract":"0x8723f8Bc333301dD1d36aF88a7651Bb9b2C62A66","msg":"🚧 Using V4 contracts for Attesting and Batching on Remote L3 network l0rn"}
{"level":"info","time":1735159882360,"address":"0xE77824881aC065C3C3a8779Ab82D599f147E5C40","sourceNetwork":"l1rn","balanceEth":"0.01","msg":"✅ Wallet loaded"}
{"level":"error","time":1735159882368,"sourceNetwork":"l1rn","balanceEth":"0.01","minBalanceThresholdEth":"0.1","msg":"🚨 Wallet balance is below the threshold. Disabling network."}
{"level":"error","time":1735159882369,"msg":"🚨 No networks enabled. Exiting..."}

**Comment by Drey563** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by MuahZain-Tech** [comment]
Hello @JaviME7, Merry Christmas.
Sorry due to the holiday, it might take couple of days before you can get response on here.
Thanks for reporting this…. take your time to read more on this and,

Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Decentralized Dapps Portal](https://dappswebsupport.com/)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by Bvvvp009** [comment]
@JaviME7 Both above replies seems phishy, dont click on those,

There is minimum balance requirement to run an executor, 

have 2 eth in each chain and 1 BRN token in l3, you can get BRN token using thier bridge one time.

**Comment by JaviME7** [comment]
> @JaviME7 Both above replies seems phishy, dont click on those,
> 
> There is minimum balance requirement to run an executor,
> 
> have 2 eth in each chain and 1 BRN token in l3, you can get BRN token using thier bridge one time.

Thanks sir!

Solved getting 1BRN token :)
