### ISSUE TITLE
Error fetching balance of destination wallet

### ISSUE THREAD

**Issue by morismc09** [t3rn/executor-release#3]
Affected version: [v0.21.0](https://github.com/t3rn/executor-release/releases/tag/v0.21.0)

When I try to start my executor with the following configuration, the node throws an error message.

Here is the Executer script:

```
#!/bin/bash

export NODE_ENV=testnet
export LOG_LEVEL=debug
export LOG_PRETTY=false
export PRIVATE_KEY_LOCAL=.....
export ENABLED_NETWORKS='arbitrum-sepolia,base-sepolia,l1rn'
./executor/bin/executor
```

This is the error message that I receive:

```
{"level":"error","time":1726259264418,"id":"0xbe3f40e161da2202a966abd0f8d4cf427af5d6ddaef1b9297b6d661bba7960de","sourceNetwork":"arbt","destinationNetwork":"opsp","asset":0,"rewardAsset":"0x0000000000000000000000000000000000000000","amount":"0.009999925045696459","maxReward":"0.01","sourceAccount":"0x8944A107B39DE50907e025e09c1B43B2344183C2","targetAccount":"0x8944a107b39de50907e025e09c1b43b2344183c2","txHash":"0x6371a9c86ea72b914c1eb5a54e1551cb84ab4c46dd1577c7c7c2faa10b3a29f6","error":"Cannot read properties of undefined (reading 'getBalance')","msg":"🚨 Error fetching balance of destination wallet"}
server-out.js:97880
        { wallet: this.wallet[order.destination].address },
                                                 ^

TypeError: Cannot read properties of undefined (reading 'address')
    at Executor.processNewOrder (server-out.js:97880:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
```

**Comment by creativebluecat** [comment]
{"level":"error","time":1726365535557,"id":"0x99450115ab4680dc4274101f5e8c6597bf6a6b4aa4585983cf745c478e3d305a","sourceNetwork":"blss","destinationNetwork":"blss","asset":0,"rewardAsset":"0x0000000000000000000000000000000000000000","amount":"0.010004560562522365","maxReward":"0.010004635021281245","sourceAccount":"0xA9E410FFCcDfeBE92a951Fed1f198c886E0Fc0B3","targetAccount":"0xa9e410ffccdfebe92a951fed1f198c886e0fc0b3","txHash":"0x9141c9b19c07c75d002c4308871a5e0f6000a2f84ecbfc848409f90f2a5351d8","error":"Cannot read properties of undefined (reading 'getBalance')","msg":"🚨 Error fetching balance of source wallet"}
server-out.js:97880
        { wallet: this.wallet[order.destination].address },
                                                 ^

TypeError: Cannot read properties of undefined (reading 'address')
    at Executor.processNewOrder (server-out.js:97880:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

**Comment by devmexican** [comment]
It is not a solution, what it does is that when the script stops it runs again
Create a sh file, run the following command

vim run_executor.sh 
copy the following code

```
#!/bin/bash

while true; do
    ./executor
    sleep 5  # Wait 5 seconds before restarting
done
```

Save the file

`Make an executable`

`chmod +x run_executor.sh`

Run 
`it: ./run_executor.sh`

**Comment by GabrielViniciusss** [comment]
i got the same problem, any solutions ?

**Comment by devmexican** [comment]
The problem of the script stopping was solved.

**Comment by 3h4x** [comment]
hey
@morismc09 @devmexican @GabrielViniciusss is it still occuring? We did fix it some time ago.
Thanks for the issue

**Comment by 3h4x** [comment]
Thanks @GabrielViniciusss . Closing then!
